# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 984931d8e1bebec1b486d9deb3fdf129decef2ac095c10ea2b0e3e1e89729b4660185d73270214a74948f2113388c4e49d3a538cbca3b7030bc2e7c381977607
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://647c12b9.ngrok.com
  paypal_email: theolupots@gmail.com

test:
  secret_key_base: 0871397b97ae7377f854286a85bb701b2db0553de45a7362c70f5e92dcc588bd9d290bef0e95c112ad4b1e7cca54ebbeba452bbfd4d03c6a6389dcbddaabfcc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: http://locodi.org
  paypal_email: theolupots@gmail.com
